punchcard-cms/content-types

README.md
lib/content-types.js
lib/content-types/load.js
lib/content-types/merge.js
tests/all.js
tests/content-types.js
tests/fixtures/content-types/bar.yml
tests/fixtures/content-types/foo.yml
tests/form.js

@Snugug 
resolves https://github.ibm.com/punchcard/punchcard-content-types/issues/15

Machine merged

---

index.js
tests/all.js

exporting form

---

lib/form/validation.js
tests/form.js

Previously, running the validation generator more than once would error out. That is no longer the case. Added tests to make sure we can do it multiple times.

Fix running validation more than once

---

README.md
lib/form.js

Forgot to expose inside the form Promise

Fix form not allowing errors to be passed in

---

lib/content-types.js

Fix the Deep Clone issue for Content Types

Fix Deep Clone objects for Content Types

---

tests/fixtures/input-plugins/input-plugin-radio.js
tests/fixtures/input-plugins/lib/validation.js

setting up tests for new input types

move input plugin to its own folder

---

lib/content-types/merge.js
lib/form/html.js
lib/form/validate.js
lib/form/validation.js
package.json
tests/content-types.js
tests/fixtures/content-types/baz.yml
tests/form.js
tests/validate.js

@Snugug 
Required check for inputs. 
Please provide feedback.

Required for input types

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
package.json

Enforces Commit Message style and GitHub stuff

Add Commit Message and GitHub Goodies

---

tests/fixtures/input-plugins/input-plugin-checkbox.js
tests/fixtures/input-plugins/input-plugin-multiple-select.js
tests/fixtures/input-plugins/input-plugin-range.js

Fixtures for input plugins.
**Changelog**
```markdown
**New**
* new fixtures for input plugin types
```
---

Plugin Fixtures

---

tests/fixtures/input-plugins/input-plugin-single.js
tests/fixtures/input-plugins/lib/input-plugin-single-select.js
tests/fixtures/input-plugins/lib/input-plugin-single-textarea.js

Additional plugins for content type testing
**Changelog**
```markdown
**New**
* input plugin single
* input plugin single textarea
* input plugin single select
```
---

Added additional plugin types

---

lib/form/scripts.js

Added in code to recognize input parent for scripts.

:bug: add code to recognize input parent for scripts

---

lib/content-types/merge.js

Fixing the path in merge.js to look for plugins

:bug: fix plugin path

---

lib/content-types/merge.js
lib/form/js/ux.js
tests/content-types.js

---
Resolves #46 
`DCO 1.1 Signed-off-by: {{Ayush Gupta}} <{{ayush2k@gmail.com}}>`

:bug: scripts for input-plugin

---

lib/form/scripts.js
tests/config/default.js
tests/form.js

Require plugins by paths instead of names.

bugfix : paths of plugins are known

---

lib/form/scripts.js

When plugins directory is not defined, seeing errors. This assures there is at least a blank array.
---
`DCO 1.1 Signed-off-by: Scott Nath<github@scottnath.com>`

bugfix: missing plugins dir

---

lib/form/html.js
lib/form/validate.js

Sets settings for pre-generated instances
---
Resolves #86 
`DCO 1.1 Signed-off-by: Ayush Gupta <ayush2k@gmail.com>`

skip required checkbox; validation setting

---

lib/content-types/only.js
lib/form/html.js
lib/form/validate.js
lib/utils.js
tests/content-types.js
tests/fixtures/objects/bar-expected.js
tests/fixtures/objects/bar-input.js

Adds function to fallback gracefully for outdated data in database
---
Resolves #90 
`DCO 1.1 Signed-off-by: Ayush Gupta <ayush2k@gmail.com>`

adds function to fallback gracefully

---

lib/content-types.js

Config not properly being passed around.
---
Resolves #100
`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

merged missing config

---

lib/form/html.js

Closes https://github.com/punchcard-cms/punchcard/issues/557

Fix placement of label closing tag

---

lib/form/html.js

Revert so label doesn't repeat

---

package.json
tests/content-types.js
tests/utils.js

Fixes ava upgrade
---
Resolves #139
`DCO 1.1 Signed-off-by: Scott Nath <github@scottnath.com>`

Upstream/greenkeeper ava 0.17.0
